### PR TITLE
WIP: Preserve PTS information

### PR DESCRIPTION
**Pull request by dmorn**
Hi there! We've noticed that the Decoder is not preserving Buffer pts information. We've a first draft for solving the problem
- Use the pts information of the first buffer to obtain a starting point
- For each frame decoded, compute its duration. Use that value to update the base pts
- Update the buffer pts field

Waiting for your feedback. (BTW, KIM is back on Membrane 😉💯)

### CODE REVIEW

**Comment by dmorn** [comment]
In our flow we have:
- FLV demuxing
- AAC audio parsing & decoding
- Transcription
- subtitle generation

With the code provided above, if we compare the pts[AAC](t) and pts[WAV](t) (computed with the above calculation, i.e., start from pts[AAC](t) and then add the actual duration of each frame) the two get out-of-sync almost immediately, pts[AAC](t) grows faster. It is expected? We use the FLV timestamp to recover the actual PTS of the stream if the pipeline connects to an RTMP stream in the middle of a live transmission.

**Comment by dmorn** [comment]
I believe this code is confusing the duration of the payload and pts, but if that is the case, how are we supposed to handle the situation in which one buffer contains more than one frame? We cannot produce buffers that have the same pts value.

**Comment by dmorn** [comment]
Maybe we could preserve a pts delta and split the pts update with the number of buffers present. Anyway, I still don't get why the to pts streams should not increase linearly together!

**Comment by dmorn** [comment]
This is wrong in many ways, updates coming.

**Comment by dmorn** [comment]
Things are complicated as:

**Comment by mat-hek** [comment]
@dmorn yeah, we generally need to refine some plugins, especially those operating on audio, amd make sure they forward timestamps properly

**Comment by dmorn** [comment]
OK, I'm reopening the PR since now with https://github.com/membraneframework/membrane_rtmp_plugin/pull/42 everything makes sense again 😆 This implementation now uses the incoming PTS (defaults to 0) as a base, then computes the PTS delta using the RawAudio.bytes_to_time function. I compared the AAC and computed PTS and they shift a bit on the microsecond range but still, this might be a worthy contribution. Check it out!

**Pull request closed without merging**
